apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa
resources:
  - ../../base
labels:
  - pairs:
      env: qa
    includeSelectors: false
    includeTemplates: true
replicas:
  - name: myapp
    count: 1
patches:
  - path: deployment-patch.yaml
images:
  - name: acrmkatf28060.azurecr.io/myapp
    newTag: v2
